language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install codecov
# command to run tests
script:
  - coverage run test.py

# Push the results back to codecov
after_success:
  - codecov